# Generated by Django 2.2.3 on 2020-03-15 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='media/images\\usruploads')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ingredients', models.TextField(max_length=512)),
                ('toolsreq', models.TextField(max_length=512)),
                ('method', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('cost', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('diettype', models.PositiveSmallIntegerField(choices=[(1, 'Meat'), (2, 'Vegetarian'), (3, 'Vegan')])),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.Category')),
                ('postedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('comment', models.TextField(blank=True, max_length=512)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='spatulaApp.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spatulaApp.Image')),
                ('belongsto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.UserProfile')),
            ],
            bases=('spatulaApp.image',),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spatulaApp.Image')),
                ('belongsto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.Recipe')),
            ],
            bases=('spatulaApp.image',),
        ),
    ]
