# Generated by Django 2.2.3 on 2020-03-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categoryForeign',
            new_name='Category',
        ),
    ]
