# Generated by Django 2.2.3 on 2020-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\natha\\OneDrive\\Documents\\GitHub\\spatula\\spatula_project\\media\\images\\images'),
        ),
    ]
