# Generated by Django 2.2.3 on 2020-03-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='postedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.UserProfile'),
        ),
    ]
