# Generated by Django 2.2.3 on 2020-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0002_auto_20200310_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to='C:\\Users\\natha\\OneDrive\\Documents\\GitHub\\spatula\\spatula_project\\media\\images\\usruploads'),
        ),
    ]
