# Generated by Django 2.2.3 on 2020-03-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0003_auto_20200306_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
    ]
