# Generated by Django 2.2.3 on 2020-03-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatulaApp', '0004_auto_20200310_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='postedby',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spatulaApp.UserProfile'),
        ),
    ]
